=== Ignaciobrenas/XML-XSD-Validation-Practices/libro.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Libro">
        <xs:complexType>
            <xs:sequence>

                
                <xs:element name="Titulo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="30"/>
                        </xs:restriction>
                    </xs:simpleType>
                    
                </xs:element>

                
                <xs:element name="Escritores">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Escritor" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                
                <xs:element name="Ediciones">
                    <xs:complexType>
                        <xs:attribute name="cantidad" type="xs:positiveInteger" use="required"/>
                    </xs:complexType>
                </xs:element>

                
                <xs:element name="Publicacion" type="xs:date"/>

                
                <xs:element name="Generos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Genero" minOccurs="1" maxOccurs="unbounded">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="fantástico"/>
                                        <xs:enumeration value="histórico"/>
                                        <xs:enumeration value="terror"/>
                                        <xs:enumeration value="thriller"/>
                                        <xs:enumeration value="humor"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Ignaciobrenas/XML-XSD-Validation-Practices/libro.xml
<?xml version="1.1" encoding="UTF-8"?>
<Libro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="libro.xsd">

    <Titulo>El libro de la selva</Titulo>

    <Escritores>
        <Escritor>Mowgli</Escritor>
    </Escritores>

    <Ediciones cantidad="67" />

    <Publicacion>2000-01-01</Publicacion>

    <Generos>
        <Genero>fantástico</Genero>
        <Genero>histórico</Genero>
    </Generos>

</Libro>
